### ISSUE TITLE
分享方法报错

### ISSUE THREAD

**Issue by zhaokuohaha** [imokya/wechat-share#2]
![image](https://user-images.githubusercontent.com/16274628/65819301-52249880-e24d-11e9-9ada-10444355f64d.png)

你好，
👆 apiurl 的问题搞定了， 但是在调用 shareToTimeline 方法的时候报了上上面这个错误， 不知道是什么原因。

**Comment by zhaokuohaha** [comment]
直接使用wx.checkJsApi 来检查代码里面那三个接口, 返回的数据也是空?  (上面截图)

**Comment by imokya** [comment]
@zhaokuohaha 感谢提醒，已经修正。
